# ==========================================================
# Parameters for the SCANNER stage (scanner.py)
# ==========================================================
scanner_params:
  min_indel_size: 1
  min_map_quality: 30
  min_base_quality: 20
  min_flank_quality: 93
  min_homopolymer_size: 3 # Used by the scanner for the denominator

# ==========================================================
# Parameters for the PROCESSOR stage (processor.py)
# ==========================================================
processor_params:
  min_homopolymer_size: 3 # Used for filtering indel objects
  min_quality: 93
  min_flank_quality: 93
