import argparse
import sys
import shutil
from pathlib import Path
from typing import Tuple, Union
import yaml
# Assuming 'logger' is configured elsewhere in your project
import logging
logger = logging.getLogger(__name__)


class BaseConfig:
	def __init__(self, args: argparse.Namespace, config_data: dict) -> None:
		
		self.args = args
		self.yaml = config_data
		self.mode = self.args.command

		# Common paths are now set based on the specific subcommand's arguments
		self.bamfile: Path = Path(self.args.bam)
		self.fastafile: Path = Path(self.args.fasta)
		
		# Output path comes from different arguments depending on the command
		if self.mode == 'scan':
			self.output_path: Path = Path(self.args.output)
		elif self.mode == 'process':
			self.output_path: Path = Path(self.args.output)
			self.input_file: Path = Path(self.args.input)


class ScannerConfig(BaseConfig):
	"""Configuration specific to the scanner mode."""
	temp_dir: Path
	min_indel_size: int
	preload: bool
	buffer_size: int
	
	def __init__(self, args: argparse.Namespace, config_data: dict):
		super().__init__(args, config_data)
		self._initialize_mode_specific_attributes()

	def _setup_output(self) -> Tuple[Path, Path]:
		"""Performs critical directory setup and cleanup for the scanner."""
		output_path = self.output_path
		self.temp_dir = output_path.parent / "temp_indel_parts"
		try:
			output_path.parent.mkdir(parents=True, exist_ok=True)
			logger.debug(f"Output directory set up at {output_path}")
			
			# CRITICAL SCANNER LOGIC: Clean up the temp directory before starting
			if self.temp_dir.exists():
				logger.info(f"Found existing temporary directory at {self.temp_dir}. Cleaning it before use.")
				shutil.rmtree(self.temp_dir)
			
			self.temp_dir.mkdir(parents=True, exist_ok=True)
			logger.debug(f"Temporary directory for partial results is ready at {self.temp_dir}")
		except Exception as e:
			logger.error(f"Error setting up output directories: {e}")
			sys.exit(1)
		return output_path, self.temp_dir

	def _initialize_mode_specific_attributes(self):
		"""Sets scanner-specific fields and executes directory setup."""
		logger.info("Configuration Mode: Scanner")
		
		# Load settings from the YAML data, with sensible defaults
		self.num_processes: int = self.yaml.get('num_processes', 4)
		self.min_indel_size:int = self.yaml.get('min_indel_size', 1)
		self.preload: bool = self.yaml.get('preload_contigs', True)
		self.buffer_size: int = self.yaml.get('write_buffer_size', 100)

		# Run Scanner-specific action: Directory setup
		self._setup_output()
		logger.info("Scanner output directories configured and cleaned.")


class ProcessorConfig(BaseConfig):
	def __init__(self, args: argparse.Namespace, config_data: dict):
		super().__init__(args, config_data)
		self._initialize_mode_specific_attributes()
		self.insertions_path: Path = self.output_path / "processed_insertions.tsv"
		self.deletions_path: Path = self.output_path / "processed_deletions.tsv"

	def _setup_output(self) -> Path:
		#Validate the primary input file exists
		if not self.input_file.is_file():
			logger.error(f"Input file not found at: {self.input_file}")
			logger.error("The 'process' command requires a valid input file generated by the 'scan' command.")
			sys.exit(1)
		
	
		#Set up the new output directory for this processing run
		try:
			# The processor should create its own output directory, but not clean it.
			self.output_path.mkdir(parents=True, exist_ok=True)
		except Exception as e:
			logger.error(f"Could not create output directory at {self.output_path}: {e}")
			sys.exit(1)
		return self.output_path


	def _initialize_mode_specific_attributes(self):
		"""Sets processor-specific fields and derives path information."""
		logger.info("Configuration Mode: Processor")
		
		# Processor derives paths from arguments, assuming they exist
		self._setup_output()
		self.output_format = self.yaml.get('output_format', 'tsv')
		logger.info(f"Processor output configured (Format: {self.output_format}). No directory cleanup performed.")


class Config:
	"""Public static factory interface to load a specialized configuration object."""

	@staticmethod
	def _parse_args() -> argparse.Namespace:
		"""Defines and parses command-line arguments."""
		parser = argparse.ArgumentParser(description="A toolkit for scanning and processing indels from BAM files.")
		subparsers = parser.add_subparsers(dest='command', required=True, help="Available commands")

		# --- Sub-parser for the 'scan' command ---
		scan_parser = subparsers.add_parser('scan', help="Scan a BAM file for indels.")
		scan_parser.add_argument("-b", "--bam", required=True, help="Input BAM file (must be indexed).")
		scan_parser.add_argument("-f", "--fasta", required=True, help="Reference FASTA file (must be indexed).")
		scan_parser.add_argument("-o", "--output", required=True, help="Path to the output directory.")
		scan_parser.add_argument("-c", "--config", default="config.yaml", help="Path to the configuration file.")
		scan_parser.add_argument("--process", action='store_true', help="Whether to process the output after scanning.")

		# --- Sub-parser for the 'process' command ---
		process_parser = subparsers.add_parser('process', help="Process the output file from the scanner.")
		process_parser.add_argument("-i", "--input", required=True, help="Input TSV file generated by the 'scan' command.")
		process_parser.add_argument("-b", "--bam", required=True, help="Input BAM file (must be indexed).")
		process_parser.add_argument("-f", "--fasta", required=True, help="Reference FASTA file.")
		process_parser.add_argument("-o", "--output", required=True, help="Path for the processed output file.")
		process_parser.add_argument("-c", "--config", default="config.yaml", help="Path to the configuration file.")
		
		return parser.parse_args()

	@staticmethod
	def load() -> Union[ScannerConfig, ProcessorConfig]:
		"""
		Factory method that parses arguments, loads the YAML config,
		and returns an instantiated and fully configured object
		of the correct subclass (ScannerConfig or ProcessorConfig).
		"""
		args = Config._parse_args()
		
		config_path = Path(args.config)
		full_config = {}
		if config_path.exists():
			try:
				with open(config_path, 'r') as f:
					full_config = yaml.safe_load(f) or {}
			except Exception as e:
				logger.error(f"Error loading configuration file {config_path}: {e}")
				sys.exit(1)
		else:
			logger.warning(f"Configuration file not found at {config_path}. Using command-line args and defaults.")
			
		# Extract the configuration section specific to the requested command (e.g., 'scan')
		mode_config = full_config.get(args.command, {})
		if not mode_config and config_path.exists():
			logger.warning(f"Configuration section '{args.command}' missing or empty in {config_path}.")

		# Factory dispatch: decide which class to instantiate and return
		if args.command == 'scan':
			return ScannerConfig(args, mode_config)
		elif args.command == 'process':
			return ProcessorConfig(args, mode_config)
		else:
			# This case should not be reached due to argparse 'required=True'
			logger.error(f"FATAL: Unknown command '{args.command}'")
			sys.exit(1)

