# indel_scanner/configurator.py
import argparse
import sys
import shutil
from pathlib import Path
from typing import Tuple, Union
import yaml
import logging

logger = logging.getLogger(__name__)


class BaseConfig:
    def __init__(self, args: argparse.Namespace, config_data: dict) -> None:
        self.args = args
        self.yaml = config_data
        self.mode = self.args.command
        self.bamfile: Path = Path(self.args.bam)
        self.fastafile: Path = Path(self.args.fasta)
        self.output_path: Path = Path(self.args.output)
        if self.mode == "process":
            self.input_file: Path = Path(self.args.input)


class ScannerConfig(BaseConfig):
    """Configuration specific to the scanner mode."""

    temp_dir: Path
    min_indel_size: int
    preload: bool
    buffer_size: int
    str_directory: Path
    min_map_quality: int
    min_base_quality: int
    min_flank_quality: int
    min_homopolymer_len: int = 3

    def __init__(self, args: argparse.Namespace, config_data: dict):
        super().__init__(args, config_data)
        self._initialize_mode_specific_attributes()

    def _setup_output(self) -> Tuple[Path, Path]:
        output_path = self.output_path
        self.temp_dir = output_path / "temp_indel_parts"
        try:
            output_path.mkdir(parents=True, exist_ok=True)
            logger.info(f"Output directory set up at {output_path}")
            if self.temp_dir.exists():
                logger.info(
                    f"Found existing temporary directory at {self.temp_dir}. Cleaning it before use."
                )
                shutil.rmtree(self.temp_dir)
            self.temp_dir.mkdir(parents=True, exist_ok=True)
            logger.debug(
                f"Temporary directory for partial results is ready at {self.temp_dir}"
            )
        except Exception as e:
            logger.error(f"Error setting up output directories: {e}")
            sys.exit(1)
        return output_path, self.temp_dir

    def _initialize_mode_specific_attributes(self):
        logger.info("Configuration Mode: Scanner")
        self.num_processes: int = self.yaml.get("num_processes", 4)
        self.min_indel_size: int = self.yaml.get("min_indel_size", 1)
        self.preload: bool = self.yaml.get("preload_contigs", True)
        self.buffer_size: int = self.yaml.get("write_buffer_size", 100)
        self.min_map_quality: int = self.yaml.get("min_map_quality", 30)
        self.min_base_quality: int = self.yaml.get("min_base_quality", 20)
        self.min_flank_quality: int = self.yaml.get("min_flank_quality", 93)
        self.str_directory: Path = Path(self.args.strdir)  # type: ignore
        self._setup_output()
        logger.info("Scanner output directories configured and cleaned.")


class ProcessorConfig(BaseConfig):
    def __init__(self, args: argparse.Namespace, config_data: dict):
        super().__init__(args, config_data)
        self._initialize_mode_specific_attributes()
        self.passed_indels_path: Path = self.output_path / "final_passed_indels.tsv"

    def _setup_output(self) -> Path:
        if not self.input_file.is_file():
            logger.error(f"Input file not found at: {self.input_file}")
            logger.error(
                "The 'process' command requires a valid input file generated by the 'scan' command."
            )
            sys.exit(1)
        try:
            self.output_path.mkdir(parents=True, exist_ok=True)
        except Exception as e:
            logger.error(
                f"Could not create output directory at {self.output_path}: {e}"
            )
            sys.exit(1)
        return self.output_path

    def _initialize_mode_specific_attributes(self):
        logger.info("Configuration Mode: Processor")
        self._setup_output()
        self.output_format = self.yaml.get("output_format", "tsv")
        logger.info(
            f"Processor output configured (Format: {self.output_format}). No directory cleanup performed."
        )


class DNM_estimateConfig(BaseConfig):
    str_directory: Path

    def __init__(self, args: argparse.Namespace, config_data: dict):
        super().__init__(args, config_data)
        self._initialize_mode_specific_attributes()

    def _initialize_mode_specific_attributes(self):
        """Sets DNM_estimate-specific fields."""
        logger.info("Configuration Mode: DNM_estimate")
        self.sampling_fraction: float = self.yaml.get("sampling_fraction", 0.01)
        self.min_homopolymer_len: int = self.yaml.get("min_homopolymer_len", 3)
        self.str_directory: Path = Path(self.args.strdir)  # type: ignore


class Config:
    @staticmethod
    def _parse_args() -> argparse.Namespace:
        parser = argparse.ArgumentParser(
            description="A toolkit for scanning and processing indels from BAM files."
        )
        subparsers = parser.add_subparsers(
            dest="command", required=True, help="Available commands"
        )
        scan_parser = subparsers.add_parser("scan", help="Scan a BAM file for indels.")
        scan_parser.add_argument(
            "-b", "--bam", required=True, help="Input BAM file (must be indexed)."
        )
        scan_parser.add_argument(
            "-f",
            "--fasta",
            required=True,
            help="Reference FASTA file (must be indexed).",
        )
        scan_parser.add_argument(
            "-o", "--output", required=True, help="Path to the output directory."
        )
        scan_parser.add_argument(
            "-c",
            "--config",
            default="config.yaml",
            help="Path to the configuration file.",
        )
        scan_parser.add_argument(
            "-s", "--strdir", required=True, help="Directory containing STR results."
        )
        scan_parser.add_argument(
            "--process",
            action="store_true",
            help="Whether to process the output after scanning.",
        )
        process_parser = subparsers.add_parser(
            "process", help="Process the output file from the scanner."
        )
        process_parser.add_argument(
            "-i",
            "--input",
            required=True,
            help="Input TSV file generated by the 'scan' command.",
        )
        process_parser.add_argument(
            "-b", "--bam", required=True, help="Input BAM file (must be indexed)."
        )
        process_parser.add_argument(
            "-f", "--fasta", required=True, help="Reference FASTA file."
        )
        process_parser.add_argument(
            "-o", "--output", required=True, help="Path for the processed output file."
        )
        process_parser.add_argument(
            "-c",
            "--config",
            default="config.yaml",
            help="Path to the configuration file.",
        )
        return parser.parse_args()

    @staticmethod
    def load() -> Union[ScannerConfig, ProcessorConfig]:
        args = Config._parse_args()
        config_path = Path(args.config)
        full_config = {}
        if config_path.exists():
            try:
                with open(config_path, "r") as f:
                    full_config = yaml.safe_load(f) or {}
            except Exception as e:
                logger.error(f"Error loading configuration file {config_path}: {e}")
                sys.exit(1)
        else:
            logger.warning(
                f"Configuration file not found at {config_path}. Using command-line args and defaults."
            )

        mode_config = full_config.get(args.command, {})
        if not mode_config and config_path.exists():
            logger.warning(
                f"Configuration section '{args.command}' missing or empty in {config_path}."
            )

        if args.command == "scan":
            return ScannerConfig(args, mode_config)
        elif args.command == "process":
            return ProcessorConfig(args, mode_config)
        else:
            logger.error(f"FATAL: Unknown command '{args.command}'")
            sys.exit(1)
