# indel_scanner/indel_scanner/main.py

import sys
import pysam
import yaml
import logging
import argparse
import time


from .utils import ScannerConfig, setup_output
from .scanner import ContigScanner
from .processor import Processor,run_processor
from .parallel import parallel_scan

logger = logging.getLogger(__name__)

def setup_logging():
	logging.basicConfig(level=logging.INFO,
						format='%(asctime)s - %(levelname)s - %(message)s',
						filename='indel_scanner.log',
						filemode='w',
						encoding='utf-8')
	
	logger.setLevel(logging.DEBUG)
	logfile = logging.FileHandler('indel_scanner.log',mode='w',encoding='utf-8',)
	logfile.setFormatter(logging.Formatter('%(asctime)s - %(levelname)s - %(message)s'))
	logfile.setLevel(logging.DEBUG)

	console = logging.StreamHandler()
	console.setLevel(logging.INFO)
	console.setFormatter(logging.Formatter('%(levelname)s - %(message)s'))

	logger.addHandler(logfile)
	logger.addHandler(console)
	

def run_scan(args):

	# --- Run in Parallel ---
	# Use functools.partial to create a version of the worker function with fixed arguments
	start_time = time.time()
	parallel_scan(args)
	end_time = time.time()

	logger.info(f"Total time taken: {end_time - start_time:.2f} seconds.")
	
def run_process(args):
	#--- Load Configuration for the processor ---
	

	run_processor(Config.ProcessorConfig(args))
	logger.info("processing indels finished")



def main():
	setup_logging()
	
	# --- Main Parser ---
	parser = argparse.ArgumentParser(
		description="A toolkit for scanning and processing indels from BAM files."
	)
	# This creates the sub-command system. 'dest' stores which command was used.
	subparsers = parser.add_subparsers(dest='command', required=True, help="Available commands")

	# --- Sub-parser for the 'scan' command ---
	scan_parser = subparsers.add_parser('scan', help="Scan a BAM file for indels.")
	scan_parser.add_argument("-b", "--bam", required=True, help="Input BAM file (must be indexed).")
	scan_parser.add_argument("-f", "--fasta", required=True, help="Reference FASTA file (must be indexed with `pyfastx index`).")
	scan_parser.add_argument("-o", "--output", required=True, help="Path to the final aggregated output TSV file.")
	scan_parser.add_argument("-c", "--config", default="config.yaml", help="Path to the configuration file.")
	scan_parser.add_argument( "--process", type=bool, default=False, help="Whether to process the output after scanning.")
	
	# --- Sub-parser for the 'process' command ---
	process_parser = subparsers.add_parser('process', help="Process the output file from the scanner.")
	process_parser.add_argument("-i", "--input", required=True, help="Input TSV file generated by the 'scan' command.")
	process_parser.add_argument("-b", "--bam", required=True, help="Input BAM file (must be indexed).")
	process_parser.add_argument("-f", "--fasta", required=True, help="Reference FASTA")
	process_parser.add_argument("-o", "--output", required=True, help="Path for the processed output file.")
	process_parser.add_argument("-c", "--config", default="config.yaml", help="Path to the configuration file.")
	

	args = parser.parse_args()

	# --- Dispatch to the correct function based on the command ---
	if args.command == 'scan':
		run_scan(args)
		if args.process:
			run_process(args)
	elif args.command == 'process':
		run_process(args)
	else:
		# This case should not be reached if 'required=True' is set for subparsers
		parser.print_help()
		sys.exit(1)

if __name__ == '__main__':
	main()
